# Generated by Django 4.0.2 on 2022-02-26 19:53

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zwift_components', '0002_alter_teamresult_dt_rowid_alter_teamresult_age_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teamresult',
            name='info_notes',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, max_length=100, null=True), size=None),
        ),
    ]
