# Generated by Django 4.0.2 on 2022-02-26 19:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zwift_components', '0004_alter_teamresult_info_notes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teamresult',
            name='skill',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='teamresult',
            name='skill_gain',
            field=models.CharField(max_length=200),
        ),
    ]
