# Generated by Django 4.0.2 on 2022-02-26 19:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zwift_components', '0005_alter_teamresult_skill_alter_teamresult_skill_gain'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teamresult',
            name='vttat',
            field=models.FloatField(),
        ),
    ]
